version: "3.8"
services:
  backend:
    image: dayrim/soulsage-backend:latest
    ports:
      - "8889:8889"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBHOOK_DOMAIN=${TELEGRAM_WEBHOOK_DOMAIN}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TELEGRAM_APP_ID=${TELEGRAM_APP_ID}
      - TELEGRAM_APP_ID_HASH=${TELEGRAM_APP_ID_HASH}
      - WEB_URL=${WEB_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  web:
    image: dayrim/soulsage-web:latest
    ports:
      - "3334:3000"
  db:
    container_name: soulsage-db-container
    image: postgres:16
    command: postgres -N 200
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ~/db/data/soulsage-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
